name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      NIX_DEV_SHELL: ci
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: totto2727-org/monorepo/.github/actions/setup-nix@main
      - uses: totto2727-org/monorepo/.github/actions/setup-moonbit@main
        with:
          dev-shell: ${{ env.NIX_DEV_SHELL }}
      - uses: totto2727-org/monorepo/.github/actions/check-moonbit@main
        with:
          dev-shell: ${{ env.NIX_DEV_SHELL }}
