name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: totto2727-org/monorepo/.github/actions/setup-nix@main
      - name: Verify Workgraph
        shell: bash
        run: |
          eval "$(nix print-dev-env "$GITHUB_WORKSPACE#default")"
          moon update
          moon info
          moon check
          moon test
